name: Bug Report
description: Report a reproducible bug in the application.
title: "[BUG] "
labels: [bug]
assignees: []

body:

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false

#  - type: textarea
#    id: actual
#    attributes:
#      label: Actual Behavior
#      description: More detail if needed.
#      placeholder: What actually happened? (more detail if needed)
#    validations:
#      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Paste logs or drag files here
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What system, browser, or version are you using?
      placeholder: |
        - OS: [e.g. Windows, MacOS, Linux]
        - Browser [e.g. Chrome, Firefox]
        - Version [e.g. 22]
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - High
        - Medium
        - Low
    validations:
      required: false