name: Pull Request
description: Submit a pull request with proper details for review.
title: "[PR] "
labels: []
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        A clear and concise description of what this pull request does.
        Include any context for the changes made.
    validations:
      required: true

  - type: dropdown
    id: type_of_change
    attributes:
      label: Type of change
      description: Select the type(s) of change included in this PR
      options:
        - Bug fix (non-breaking change)
        - New feature (non-breaking change)
        - Breaking change
        - Documentation update
    validations:
      required: true
      multiple: true

  - type: textarea
    id: how_tested
    attributes:
      label: How Has This Been Tested?
      placeholder: |
        Describe how you tested your changes.
        Examples:
        - Ran the application locally
        - Created and ran unittests
        - Used DevTools to monitor calls and data
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Make sure all of the following apply before submitting the PR
      options:
        - I have followed the coding style guidelines of this project
        - I have reviewed my own code
        - I have commented hard-to-understand areas
        - I have added docstrings to all public functions/methods
        - I have used descriptive variable names
        - I have made corresponding changes to the documentation
        - I have added tests that prove my feature works or fix is effective
        - New and existing unit tests pass locally with my changes
    validations:
      required: false

  - type: textarea
    id: related_issue
    attributes:
      label: Related Issue(s)
      description: Reference related issues or tickets, if applicable (e.g., Closes #1)
      placeholder: e.g. Closes #123
    validations:
      required: false
